title:<p align="center"> Inderpreet Arora </p>
logo: /assets/img/logo.png
description:  <p align="center">
  <a href="https://github.com/inderpreetarora">GitHub</a>
  <br>   
  I work on Embedded systems, Digital control and Machine learning projects for automotive and manufacturing units. 
  <br>
  </p>

theme: jekyll-theme-minimal
